name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary pytest pytest-mock

      - name: Package Lambda function
        run: |
          mkdir -p package
          cp lambda_function.py package/
          cd package
          zip -r ../lambda_function.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        run: |
          if aws lambda get-function --function-name login; then
            aws lambda update-function-code --function-name login --zip-file fileb://lambda_function.zip
            aws lambda update-function-configuration --function-name login --timeout 600 --vpc-config SubnetIds=subnet-07daf515b678c9259,subnet-0843c227a61d10bb5,SecurityGroupIds=sg-0e22de86e3b608b71
          else
            aws lambda create-function --function-name login --runtime python3.8 --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/lambda_exec_role_NkIxpPdd --handler lambda_function.lambda_handler --zip-file fileb://lambda_function.zip --timeout 600 --vpc-config SubnetIds=subnet-07daf515b678c9259,subnet-0843c227a61d10bb5,SecurityGroupIds=sg-0e22de86e3b608b71
          fi

      - name: Wait for Lambda function update
        run: |
          while [[ $(aws lambda get-function --function-name login --query 'Configuration.LastUpdateStatus') == '"InProgress"' ]]; do
            echo "Waiting for Lambda function update to complete..."
            sleep 10
          done

      - name: Run unit tests
        run: |
          python -m pytest test_lambda_function.py
